source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'LearningApp' do
  use_frameworks!

  # Pods for LearningApp
  pod 'MarketingCloudSDK'
  pod 'SFPushFeatureSDK'
  pod 'SFMobileAppMessagingSDK'
  pod 'SFInAppMessagingFeatureSDK'
end

target 'MarketingCloudServiceExtension' do
  use_frameworks!

  # Pods for MarketingCloudServiceExtension
  pod 'MarketingCloud-ExtensionSDK'
end

target 'MarketingCloudContentExtension' do
  use_frameworks!

  # Pods for MarketingCloudContentExtension
  pod 'MarketingCloud-ExtensionSDK'
end
