#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef MARKETINGCLOUDSDK_SWIFT_H
#define MARKETINGCLOUDSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import SFMCSDK;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MarketingCloudSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


@class NSString;

SWIFT_CLASS("_TtC17MarketingCloudSDK10PushConfig")
@interface PushConfig : NSObject <SFMCSdkModuleConfig>
@property (nonatomic, readonly) enum SFMCSdkModuleName name;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
@class NSNumber;

SWIFT_CLASS("_TtC17MarketingCloudSDK17PushConfigBuilder")
@interface PushConfigBuilder : NSObject
- (nonnull instancetype)initWithAppId:(NSString * _Nonnull)appId OBJC_DESIGNATED_INITIALIZER;
- (PushConfigBuilder * _Nonnull)setAccessToken:(NSString * _Nonnull)accessToken SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setMarketingCloudServerUrl:(NSURL * _Nonnull)endpoint SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setMid:(NSString * _Nonnull)mid SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setLocationEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setInboxEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setAnalyticsEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setPIAnalyticsEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setUseLegacyPIIdentifier:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setApplicationControlsBadging:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setDelayRegistrationUntilContactKeyIsSet:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfig * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SFMCSdkModuleLogger;
@protocol SFMCSdkModuleIdentity;
@class Message;
@class SFMCEvent;
@class NSData;
@class UNNotificationRequest;
@protocol SFMCSdkInAppMessageEventDelegate;
@class UITableView;
@protocol SFMCSdkInboxMessagesDataSource;
@protocol SFMCSdkInboxMessagesDelegate;
@protocol SFMCSdkLocationDelegate;
@class CLRegion;
@protocol SFMCSdkURLHandlingDelegate;
@class SFMCSdkComponents;

SWIFT_CLASS_NAMED("PushModule")
@interface SFMCSdkPushModule : NSObject <PushInterface, SFMCModule, Subscriber>
@property (nonatomic) enum SFMCSdkModuleName name;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull moduleVersion;)
+ (NSString * _Nonnull)moduleVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)setModuleVersion:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSDictionary<NSString *, NSString *> * _Nullable stateProperties;)
+ (NSDictionary<NSString *, NSString *> * _Nullable)stateProperties SWIFT_WARN_UNUSED_RESULT;
+ (void)setStateProperties:(NSDictionary<NSString *, NSString *> * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum ModuleStatus status;)
+ (enum ModuleStatus)status SWIFT_WARN_UNUSED_RESULT;
+ (void)setStatus:(enum ModuleStatus)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFMCSdkPushModule * _Nonnull shared;)
+ (SFMCSdkPushModule * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFMCSdkModuleLogger * _Nonnull logger;)
+ (SFMCSdkModuleLogger * _Nonnull)logger SWIFT_WARN_UNUSED_RESULT;
+ (SFMCSdkModuleLogger * _Nonnull)getLogger SWIFT_WARN_UNUSED_RESULT;
- (id <SFMCSdkModuleIdentity> _Nullable)getIdentity SWIFT_WARN_UNUSED_RESULT;
- (void)receiveWithMessage:(Message * _Nonnull)message;
+ (void)sendSfmcEvent:(SFMCEvent * _Nonnull)event category:(enum SFMCSdkEventCategory)category;
+ (void)sendIdentityEventForTags;
+ (void)sendIdentityEventForContactKey;
+ (void)sendIdentityEventForAttributes;
+ (NSDictionary<NSString *, id> * _Nonnull)metadata SWIFT_WARN_UNUSED_RESULT;
- (void)tearDown;
- (NSString * _Nullable)contactKey SWIFT_WARN_UNUSED_RESULT;
- (BOOL)addTag:(NSString * _Nonnull)tag SWIFT_WARN_UNUSED_RESULT;
- (NSSet * _Nullable)addTags:(NSArray * _Nonnull)tags SWIFT_WARN_UNUSED_RESULT;
- (BOOL)removeTag:(NSString * _Nonnull)tag SWIFT_WARN_UNUSED_RESULT;
- (NSSet * _Nullable)tags SWIFT_WARN_UNUSED_RESULT;
- (void)setDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)setDebugLoggingEnabled:(BOOL)enabled;
- (NSString * _Nullable)deviceToken SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)accessToken SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)deviceIdentifier SWIFT_WARN_UNUSED_RESULT;
- (void)setNotificationRequest:(UNNotificationRequest * _Nonnull)request;
- (UNNotificationRequest * _Nullable)notificationRequest SWIFT_WARN_UNUSED_RESULT;
- (void)setNotificationUserInfo:(NSDictionary * _Nonnull)userInfo;
- (NSDictionary * _Nonnull)notificationUserInfo SWIFT_WARN_UNUSED_RESULT;
- (void)setPushEnabled:(BOOL)pushEnabled;
- (BOOL)pushEnabled SWIFT_WARN_UNUSED_RESULT;
- (BOOL)refreshWithFetchCompletionHandler:(void (^ _Nullable)(UIBackgroundFetchResult))completionHandler SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setSignedString:(NSString * _Nullable)signedString SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)signedString SWIFT_WARN_UNUSED_RESULT;
- (void)setEventDelegate:(id <SFMCSdkInAppMessageEventDelegate> _Nullable)delegate;
- (NSString * _Nullable)messageIdForMessage:(NSDictionary * _Nonnull)forMessage SWIFT_WARN_UNUSED_RESULT;
- (void)showInAppMessageWithMessageId:(NSString * _Nonnull)messageId;
- (BOOL)setInAppMessageWithFontName:(NSString * _Nullable)fontName SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getAllMessages SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getUnreadMessages SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getReadMessages SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getDeletedMessages SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getAllMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getUnreadMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getReadMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getDeletedMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageRead:(NSDictionary * _Nonnull)messageDictionary SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageDeleted:(NSDictionary * _Nonnull)messageDictionary SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageWithIdReadWithMessageId:(NSString * _Nonnull)messageId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageWithIdDeletedWithMessageId:(NSString * _Nonnull)messageId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markAllMessagesRead SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markAllMessagesDeleted SWIFT_WARN_UNUSED_RESULT;
- (BOOL)refreshMessages SWIFT_WARN_UNUSED_RESULT;
- (id <SFMCSdkInboxMessagesDataSource> _Nullable)inboxMessagesTableViewDataSourceForTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (id <SFMCSdkInboxMessagesDelegate> _Nullable)inboxMessagesTableViewDelegateForTableView:(UITableView * _Nonnull)tableView dataSource:(id <SFMCSdkInboxMessagesDataSource> _Nonnull)dataSource SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setPiIdentifier:(NSString * _Nullable)identifier SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)piIdentifier SWIFT_WARN_UNUSED_RESULT;
- (void)trackMessageOpened:(NSDictionary * _Nonnull)inboxMessage;
- (void)trackPageViewWithUrl:(NSString * _Nonnull)url title:(NSString * _Nullable)title item:(NSString * _Nullable)item search:(NSString * _Nullable)search;
- (void)trackCartContents:(NSDictionary * _Nonnull)cartDictionary;
- (void)trackCartConversion:(NSDictionary * _Nonnull)orderDictionary;
- (NSDictionary * _Nullable)cartItemDictionaryWithPrice:(NSNumber * _Nonnull)price quantity:(NSNumber * _Nonnull)quantity item:(NSString * _Nonnull)item uniqueId:(NSString * _Nullable)uniqueId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nullable)cartDictionaryWithCartItem:(NSArray * _Nonnull)cartItem SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nullable)orderDictionaryWithOrderNumber:(NSString * _Nonnull)orderNumber shipping:(NSNumber * _Nonnull)shipping discount:(NSNumber * _Nonnull)discount cart:(NSDictionary * _Nonnull)cart SWIFT_WARN_UNUSED_RESULT;
- (void)setLocationDelegate:(id <SFMCSdkLocationDelegate> _Nullable)delegate;
- (CLRegion * _Nullable)regionFromDictionary:(NSDictionary * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (BOOL)locationEnabled SWIFT_WARN_UNUSED_RESULT;
- (void)startWatchingLocation;
- (void)stopWatchingLocation;
- (BOOL)watchingLocation SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nullable)lastKnownLocation SWIFT_WARN_UNUSED_RESULT;
- (void)setURLHandlingDelegate:(id <SFMCSdkURLHandlingDelegate> _Nullable)delegate;
+ (id <SFMCModule> _Nullable)initModuleWithConfig:(id <SFMCSdkModuleConfig> _Nonnull)config components:(SFMCSdkComponents * _Nonnull)components SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7S__) && __ARM_ARCH_7S__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef MARKETINGCLOUDSDK_SWIFT_H
#define MARKETINGCLOUDSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import SFMCSDK;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MarketingCloudSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


@class NSString;

SWIFT_CLASS("_TtC17MarketingCloudSDK10PushConfig")
@interface PushConfig : NSObject <SFMCSdkModuleConfig>
@property (nonatomic, readonly) enum SFMCSdkModuleName name;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
@class NSNumber;

SWIFT_CLASS("_TtC17MarketingCloudSDK17PushConfigBuilder")
@interface PushConfigBuilder : NSObject
- (nonnull instancetype)initWithAppId:(NSString * _Nonnull)appId OBJC_DESIGNATED_INITIALIZER;
- (PushConfigBuilder * _Nonnull)setAccessToken:(NSString * _Nonnull)accessToken SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setMarketingCloudServerUrl:(NSURL * _Nonnull)endpoint SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setMid:(NSString * _Nonnull)mid SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setLocationEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setInboxEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setAnalyticsEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setPIAnalyticsEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setUseLegacyPIIdentifier:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setApplicationControlsBadging:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setDelayRegistrationUntilContactKeyIsSet:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfig * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SFMCSdkModuleLogger;
@protocol SFMCSdkModuleIdentity;
@class Message;
@class SFMCEvent;
@class NSData;
@class UNNotificationRequest;
@protocol SFMCSdkInAppMessageEventDelegate;
@class UITableView;
@protocol SFMCSdkInboxMessagesDataSource;
@protocol SFMCSdkInboxMessagesDelegate;
@protocol SFMCSdkLocationDelegate;
@class CLRegion;
@protocol SFMCSdkURLHandlingDelegate;
@class SFMCSdkComponents;

SWIFT_CLASS_NAMED("PushModule")
@interface SFMCSdkPushModule : NSObject <PushInterface, SFMCModule, Subscriber>
@property (nonatomic) enum SFMCSdkModuleName name;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull moduleVersion;)
+ (NSString * _Nonnull)moduleVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)setModuleVersion:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSDictionary<NSString *, NSString *> * _Nullable stateProperties;)
+ (NSDictionary<NSString *, NSString *> * _Nullable)stateProperties SWIFT_WARN_UNUSED_RESULT;
+ (void)setStateProperties:(NSDictionary<NSString *, NSString *> * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum ModuleStatus status;)
+ (enum ModuleStatus)status SWIFT_WARN_UNUSED_RESULT;
+ (void)setStatus:(enum ModuleStatus)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFMCSdkPushModule * _Nonnull shared;)
+ (SFMCSdkPushModule * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFMCSdkModuleLogger * _Nonnull logger;)
+ (SFMCSdkModuleLogger * _Nonnull)logger SWIFT_WARN_UNUSED_RESULT;
+ (SFMCSdkModuleLogger * _Nonnull)getLogger SWIFT_WARN_UNUSED_RESULT;
- (id <SFMCSdkModuleIdentity> _Nullable)getIdentity SWIFT_WARN_UNUSED_RESULT;
- (void)receiveWithMessage:(Message * _Nonnull)message;
+ (void)sendSfmcEvent:(SFMCEvent * _Nonnull)event category:(enum SFMCSdkEventCategory)category;
+ (void)sendIdentityEventForTags;
+ (void)sendIdentityEventForContactKey;
+ (void)sendIdentityEventForAttributes;
+ (NSDictionary<NSString *, id> * _Nonnull)metadata SWIFT_WARN_UNUSED_RESULT;
- (void)tearDown;
- (NSString * _Nullable)contactKey SWIFT_WARN_UNUSED_RESULT;
- (BOOL)addTag:(NSString * _Nonnull)tag SWIFT_WARN_UNUSED_RESULT;
- (NSSet * _Nullable)addTags:(NSArray * _Nonnull)tags SWIFT_WARN_UNUSED_RESULT;
- (BOOL)removeTag:(NSString * _Nonnull)tag SWIFT_WARN_UNUSED_RESULT;
- (NSSet * _Nullable)tags SWIFT_WARN_UNUSED_RESULT;
- (void)setDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)setDebugLoggingEnabled:(BOOL)enabled;
- (NSString * _Nullable)deviceToken SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)accessToken SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)deviceIdentifier SWIFT_WARN_UNUSED_RESULT;
- (void)setNotificationRequest:(UNNotificationRequest * _Nonnull)request;
- (UNNotificationRequest * _Nullable)notificationRequest SWIFT_WARN_UNUSED_RESULT;
- (void)setNotificationUserInfo:(NSDictionary * _Nonnull)userInfo;
- (NSDictionary * _Nonnull)notificationUserInfo SWIFT_WARN_UNUSED_RESULT;
- (void)setPushEnabled:(BOOL)pushEnabled;
- (BOOL)pushEnabled SWIFT_WARN_UNUSED_RESULT;
- (BOOL)refreshWithFetchCompletionHandler:(void (^ _Nullable)(UIBackgroundFetchResult))completionHandler SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setSignedString:(NSString * _Nullable)signedString SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)signedString SWIFT_WARN_UNUSED_RESULT;
- (void)setEventDelegate:(id <SFMCSdkInAppMessageEventDelegate> _Nullable)delegate;
- (NSString * _Nullable)messageIdForMessage:(NSDictionary * _Nonnull)forMessage SWIFT_WARN_UNUSED_RESULT;
- (void)showInAppMessageWithMessageId:(NSString * _Nonnull)messageId;
- (BOOL)setInAppMessageWithFontName:(NSString * _Nullable)fontName SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getAllMessages SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getUnreadMessages SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getReadMessages SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getDeletedMessages SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getAllMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getUnreadMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getReadMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getDeletedMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageRead:(NSDictionary * _Nonnull)messageDictionary SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageDeleted:(NSDictionary * _Nonnull)messageDictionary SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageWithIdReadWithMessageId:(NSString * _Nonnull)messageId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageWithIdDeletedWithMessageId:(NSString * _Nonnull)messageId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markAllMessagesRead SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markAllMessagesDeleted SWIFT_WARN_UNUSED_RESULT;
- (BOOL)refreshMessages SWIFT_WARN_UNUSED_RESULT;
- (id <SFMCSdkInboxMessagesDataSource> _Nullable)inboxMessagesTableViewDataSourceForTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (id <SFMCSdkInboxMessagesDelegate> _Nullable)inboxMessagesTableViewDelegateForTableView:(UITableView * _Nonnull)tableView dataSource:(id <SFMCSdkInboxMessagesDataSource> _Nonnull)dataSource SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setPiIdentifier:(NSString * _Nullable)identifier SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)piIdentifier SWIFT_WARN_UNUSED_RESULT;
- (void)trackMessageOpened:(NSDictionary * _Nonnull)inboxMessage;
- (void)trackPageViewWithUrl:(NSString * _Nonnull)url title:(NSString * _Nullable)title item:(NSString * _Nullable)item search:(NSString * _Nullable)search;
- (void)trackCartContents:(NSDictionary * _Nonnull)cartDictionary;
- (void)trackCartConversion:(NSDictionary * _Nonnull)orderDictionary;
- (NSDictionary * _Nullable)cartItemDictionaryWithPrice:(NSNumber * _Nonnull)price quantity:(NSNumber * _Nonnull)quantity item:(NSString * _Nonnull)item uniqueId:(NSString * _Nullable)uniqueId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nullable)cartDictionaryWithCartItem:(NSArray * _Nonnull)cartItem SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nullable)orderDictionaryWithOrderNumber:(NSString * _Nonnull)orderNumber shipping:(NSNumber * _Nonnull)shipping discount:(NSNumber * _Nonnull)discount cart:(NSDictionary * _Nonnull)cart SWIFT_WARN_UNUSED_RESULT;
- (void)setLocationDelegate:(id <SFMCSdkLocationDelegate> _Nullable)delegate;
- (CLRegion * _Nullable)regionFromDictionary:(NSDictionary * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (BOOL)locationEnabled SWIFT_WARN_UNUSED_RESULT;
- (void)startWatchingLocation;
- (void)stopWatchingLocation;
- (BOOL)watchingLocation SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nullable)lastKnownLocation SWIFT_WARN_UNUSED_RESULT;
- (void)setURLHandlingDelegate:(id <SFMCSdkURLHandlingDelegate> _Nullable)delegate;
+ (id <SFMCModule> _Nullable)initModuleWithConfig:(id <SFMCSdkModuleConfig> _Nonnull)config components:(SFMCSdkComponents * _Nonnull)components SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef MARKETINGCLOUDSDK_SWIFT_H
#define MARKETINGCLOUDSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import SFMCSDK;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MarketingCloudSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


@class NSString;

SWIFT_CLASS("_TtC17MarketingCloudSDK10PushConfig")
@interface PushConfig : NSObject <SFMCSdkModuleConfig>
@property (nonatomic, readonly) enum SFMCSdkModuleName name;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
@class NSNumber;

SWIFT_CLASS("_TtC17MarketingCloudSDK17PushConfigBuilder")
@interface PushConfigBuilder : NSObject
- (nonnull instancetype)initWithAppId:(NSString * _Nonnull)appId OBJC_DESIGNATED_INITIALIZER;
- (PushConfigBuilder * _Nonnull)setAccessToken:(NSString * _Nonnull)accessToken SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setMarketingCloudServerUrl:(NSURL * _Nonnull)endpoint SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setMid:(NSString * _Nonnull)mid SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setLocationEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setInboxEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setAnalyticsEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setPIAnalyticsEnabled:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setUseLegacyPIIdentifier:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setApplicationControlsBadging:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfigBuilder * _Nonnull)setDelayRegistrationUntilContactKeyIsSet:(BOOL)enabled SWIFT_WARN_UNUSED_RESULT;
- (PushConfig * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SFMCSdkModuleLogger;
@protocol SFMCSdkModuleIdentity;
@class Message;
@class SFMCEvent;
@class NSData;
@class UNNotificationRequest;
@protocol SFMCSdkInAppMessageEventDelegate;
@class UITableView;
@protocol SFMCSdkInboxMessagesDataSource;
@protocol SFMCSdkInboxMessagesDelegate;
@protocol SFMCSdkLocationDelegate;
@class CLRegion;
@protocol SFMCSdkURLHandlingDelegate;
@class SFMCSdkComponents;

SWIFT_CLASS_NAMED("PushModule")
@interface SFMCSdkPushModule : NSObject <PushInterface, SFMCModule, Subscriber>
@property (nonatomic) enum SFMCSdkModuleName name;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull moduleVersion;)
+ (NSString * _Nonnull)moduleVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)setModuleVersion:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSDictionary<NSString *, NSString *> * _Nullable stateProperties;)
+ (NSDictionary<NSString *, NSString *> * _Nullable)stateProperties SWIFT_WARN_UNUSED_RESULT;
+ (void)setStateProperties:(NSDictionary<NSString *, NSString *> * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum ModuleStatus status;)
+ (enum ModuleStatus)status SWIFT_WARN_UNUSED_RESULT;
+ (void)setStatus:(enum ModuleStatus)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFMCSdkPushModule * _Nonnull shared;)
+ (SFMCSdkPushModule * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SFMCSdkModuleLogger * _Nonnull logger;)
+ (SFMCSdkModuleLogger * _Nonnull)logger SWIFT_WARN_UNUSED_RESULT;
+ (SFMCSdkModuleLogger * _Nonnull)getLogger SWIFT_WARN_UNUSED_RESULT;
- (id <SFMCSdkModuleIdentity> _Nullable)getIdentity SWIFT_WARN_UNUSED_RESULT;
- (void)receiveWithMessage:(Message * _Nonnull)message;
+ (void)sendSfmcEvent:(SFMCEvent * _Nonnull)event category:(enum SFMCSdkEventCategory)category;
+ (void)sendIdentityEventForTags;
+ (void)sendIdentityEventForContactKey;
+ (void)sendIdentityEventForAttributes;
+ (NSDictionary<NSString *, id> * _Nonnull)metadata SWIFT_WARN_UNUSED_RESULT;
- (void)tearDown;
- (NSString * _Nullable)contactKey SWIFT_WARN_UNUSED_RESULT;
- (BOOL)addTag:(NSString * _Nonnull)tag SWIFT_WARN_UNUSED_RESULT;
- (NSSet * _Nullable)addTags:(NSArray * _Nonnull)tags SWIFT_WARN_UNUSED_RESULT;
- (BOOL)removeTag:(NSString * _Nonnull)tag SWIFT_WARN_UNUSED_RESULT;
- (NSSet * _Nullable)tags SWIFT_WARN_UNUSED_RESULT;
- (void)setDeviceToken:(NSData * _Nonnull)deviceToken;
- (void)setDebugLoggingEnabled:(BOOL)enabled;
- (NSString * _Nullable)deviceToken SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nullable)attributes SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)accessToken SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)deviceIdentifier SWIFT_WARN_UNUSED_RESULT;
- (void)setNotificationRequest:(UNNotificationRequest * _Nonnull)request;
- (UNNotificationRequest * _Nullable)notificationRequest SWIFT_WARN_UNUSED_RESULT;
- (void)setNotificationUserInfo:(NSDictionary * _Nonnull)userInfo;
- (NSDictionary * _Nonnull)notificationUserInfo SWIFT_WARN_UNUSED_RESULT;
- (void)setPushEnabled:(BOOL)pushEnabled;
- (BOOL)pushEnabled SWIFT_WARN_UNUSED_RESULT;
- (BOOL)refreshWithFetchCompletionHandler:(void (^ _Nullable)(UIBackgroundFetchResult))completionHandler SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setSignedString:(NSString * _Nullable)signedString SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)signedString SWIFT_WARN_UNUSED_RESULT;
- (void)setEventDelegate:(id <SFMCSdkInAppMessageEventDelegate> _Nullable)delegate;
- (NSString * _Nullable)messageIdForMessage:(NSDictionary * _Nonnull)forMessage SWIFT_WARN_UNUSED_RESULT;
- (void)showInAppMessageWithMessageId:(NSString * _Nonnull)messageId;
- (BOOL)setInAppMessageWithFontName:(NSString * _Nullable)fontName SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getAllMessages SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getUnreadMessages SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getReadMessages SWIFT_WARN_UNUSED_RESULT;
- (NSArray * _Nullable)getDeletedMessages SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getAllMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getUnreadMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getReadMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getDeletedMessagesCount SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageRead:(NSDictionary * _Nonnull)messageDictionary SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageDeleted:(NSDictionary * _Nonnull)messageDictionary SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageWithIdReadWithMessageId:(NSString * _Nonnull)messageId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markMessageWithIdDeletedWithMessageId:(NSString * _Nonnull)messageId SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markAllMessagesRead SWIFT_WARN_UNUSED_RESULT;
- (BOOL)markAllMessagesDeleted SWIFT_WARN_UNUSED_RESULT;
- (BOOL)refreshMessages SWIFT_WARN_UNUSED_RESULT;
- (id <SFMCSdkInboxMessagesDataSource> _Nullable)inboxMessagesTableViewDataSourceForTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (id <SFMCSdkInboxMessagesDelegate> _Nullable)inboxMessagesTableViewDelegateForTableView:(UITableView * _Nonnull)tableView dataSource:(id <SFMCSdkInboxMessagesDataSource> _Nonnull)dataSource SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setPiIdentifier:(NSString * _Nullable)identifier SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)piIdentifier SWIFT_WARN_UNUSED_RESULT;
- (void)trackMessageOpened:(NSDictionary * _Nonnull)inboxMessage;
- (void)trackPageViewWithUrl:(NSString * _Nonnull)url title:(NSString * _Nullable)title item:(NSString * _Nullable)item search:(NSString * _Nullable)search;
- (void)trackCartContents:(NSDictionary * _Nonnull)cartDictionary;
- (void)trackCartConversion:(NSDictionary * _Nonnull)orderDictionary;
- (NSDictionary * _Nullable)cartItemDictionaryWithPrice:(NSNumber * _Nonnull)price quantity:(NSNumber * _Nonnull)quantity item:(NSString * _Nonnull)item uniqueId:(NSString * _Nullable)uniqueId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nullable)cartDictionaryWithCartItem:(NSArray * _Nonnull)cartItem SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary * _Nullable)orderDictionaryWithOrderNumber:(NSString * _Nonnull)orderNumber shipping:(NSNumber * _Nonnull)shipping discount:(NSNumber * _Nonnull)discount cart:(NSDictionary * _Nonnull)cart SWIFT_WARN_UNUSED_RESULT;
- (void)setLocationDelegate:(id <SFMCSdkLocationDelegate> _Nullable)delegate;
- (CLRegion * _Nullable)regionFromDictionary:(NSDictionary * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
- (BOOL)locationEnabled SWIFT_WARN_UNUSED_RESULT;
- (void)startWatchingLocation;
- (void)stopWatchingLocation;
- (BOOL)watchingLocation SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nullable)lastKnownLocation SWIFT_WARN_UNUSED_RESULT;
- (void)setURLHandlingDelegate:(id <SFMCSdkURLHandlingDelegate> _Nullable)delegate;
+ (id <SFMCModule> _Nullable)initModuleWithConfig:(id <SFMCSdkModuleConfig> _Nonnull)config components:(SFMCSdkComponents * _Nonnull)components SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
