source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'LearningAppMPP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearningAppMPP
  pod 'MarketingCloudSDK'
  pod 'MarketingCloud-SFMCSdk'

  #Add firebase Pod 

end
